apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  interval: 10m0s
  url: https://github.com/rancher/local-path-provisioner/tree/master/deploy/chart/local-path-provisioner
