apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telegraf-ds
  namespace: monitor
spec:
  releaseName: telegraf-ds
  chart:
    spec:
      chart: telegraf-ds
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: telegraf-ds
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "100m"
        memory: "500Mi"
    config:
      docker: false
      docker_endpoint: ""
