apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garge-api
  namespace: garge-dev
spec:
  chart:
    spec:
      chart: garge-api
      version: ${GARGE_API_VERSION} # Set in postBuild production
  values:
    env:
      - name: JWT__KEY
        secretKeyRef:
          key: JWT__KEY
          name: garge-api-secrets
      - name: JWT__ISSUER
        secretKeyRef:
          key: JWT__ISSUER
          name: garge-api-secrets
      - name: CONNECTIONSTRINGS__DEFAULTCONNECTION
        secretKeyRef:
          key: CONNECTIONSTRINGS__DEFAULTCONNECTION
          name: garge-api-secrets
      - name: SENDGRIDSETTINGS__APIKEY
        secretKeyRef:
          key: SENDGRIDSETTINGS__APIKEY
          name: garge-api-secrets
      - name: SENDGRIDSETTINGS__SENDEREMAIL
        secretKeyRef:
          key: SENDGRIDSETTINGS__SENDEREMAIL
          name: garge-api-secrets
      - name: SENDGRIDSETTINGS__SENDERNAME
        secretKeyRef:
          key: SENDGRIDSETTINGS__SENDERNAME
          name: garge-api-secrets
    image:
      tag: "dev"
      pullPolicy: Always
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: garge-api-dev.prod.tumogroup.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: garge-api-tls
          hosts:
            - garge-api-dev.prod.tumogroup.com
    resources:
      requests:
        memory: "1024Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garge-api
  namespace: garge-prod
spec:
  chart:
    spec:
      chart: garge-api
      version: ${GARGE_API_VERSION} # Set in postBuild production
  values:
    env:
      - name: JWT__KEY
        secretKeyRef:
          key: JWT__KEY
          name: garge-api-secrets
      - name: JWT__ISSUER
        secretKeyRef:
          key: JWT__ISSUER
          name: garge-api-secrets
      - name: CONNECTIONSTRINGS__DEFAULTCONNECTION
        secretKeyRef:
          key: CONNECTIONSTRINGS__DEFAULTCONNECTION
          name: garge-api-secrets
    image:
      tag: "v1.0.0"
      pullPolicy: Always
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: garge-api.prod.tumogroup.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: garge-api-tls
          hosts:
            - garge-api.prod.tumogroup.com
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"