apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-config
  namespace: home-assistant-et
  annotations:
    meta.helm.sh/release-name: home-assistant-et
    meta.helm.sh/release-namespace: home-assistant-et
  labels:
    app.kubernetes.io/managed-by: Helm
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:
    default_config_exclude:
      early_loader_hook: true
      exclude:
        - dhcp
        - ssdp
        - cloud
        - zeroconf
        - energy
        - map
        - media_source

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    # automation: !include automations.yaml
    # script: !include scripts.yaml
    # scene: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 127.0.0.1
        - 192.168.0.0/16
        - 192.169.0.0/16
