apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant-et
  namespace: home-assistant-et
spec:
  releaseName: home-assistant-et
  chart:
    spec:
      chart: home-assistant
      version: 0.5.12 # Set in postBuild production
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  values:
    service:
      port: 8124
    persistence:
      enabled: true
      storageClass: freenas-nfs-csi
      size: 10Gi
      additionalVolumes:
        - name: config-volume
          configMap:
            name: home-assistant-config
      additionalMounts:
        - name: config-volume
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
  interval: 15m
  timeout: 5m
