apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kubernetes-storage-et
  annotations:
    meta.helm.sh/release-name: home-assistant-et
    meta.helm.sh/release-namespace: home-assistant-et
  labels:
    app.kubernetes.io/managed-by: Helm
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer