apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nstuning-redirect
  namespace: nstuning-prod
  annotations:
    meta.helm.sh/release-name: nstuning-app
    meta.helm.sh/release-namespace: nstuning-prod
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.nstuning.no$request_uri"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - nstuning.no
    secretName: nstuning-app-redirect-tls
  rules:
    - host: nstuning.no
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dummy-service
                port:
                  number: 80
