apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garge-operator
  namespace: garge-dev
spec:
  chart:
    spec:
      chart: garge-operator
      version: ${GARGE_OPERATOR_VERSION} # Set in postBuild production
  values:
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garge-operator
  namespace: garge-prod
spec:
  chart:
    spec:
      chart: garge-operator
      version: ${GARGE_OPERATOR_VERSION} # Set in postBuild production
  values:
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"