apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  chart:
    spec:
      version: ${MYSQL_VERSION} # Set in postBuild production
  values:
    primary:
      persistence:
        configuration: |
          [mysqld]
          default_authentication_plugin=mysql_native_password
        enabled: true
        storageClass: nfs
        size: 8Gi
    auth:
      database: grafana
      username: grafana
      # authenticationPolicy: caching_sha2_password
