apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  chart:
    spec:
      version: ${MYSQL_VERSION} # Set in postBuild production
  values:
    primary:
      persistence:
        configuration: |-
            [mysqld]
            default_authentication_plugin=mysql_native_password
            mysql_native_password=ON
            skip-name-resolve
            explicit_defaults_for_timestamp
            basedir=/opt/bitnami/mysql
            plugin_dir=/opt/bitnami/mysql/lib/plugin
            port={{ .Values.primary.containerPorts.mysql }}
            mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
            mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
            socket=/opt/bitnami/mysql/tmp/mysql.sock
            datadir=/bitnami/mysql/data
            tmpdir=/opt/bitnami/mysql/tmp
            max_allowed_packet=16M
            bind-address=*
            pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
            log-error=/opt/bitnami/mysql/logs/mysqld.log
            character-set-server=UTF8
            slow_query_log=0
            long_query_time=10.0

            [client]
            port={{ .Values.primary.containerPorts.mysql }}
            socket=/opt/bitnami/mysql/tmp/mysql.sock
            default-character-set=UTF8
            plugin_dir=/opt/bitnami/mysql/lib/plugin

            [manager]
            port={{ .Values.primary.containerPorts.mysql }}
            socket=/opt/bitnami/mysql/tmp/mysql.sock
            pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
        enabled: true
        storageClass: nfs
        size: 8Gi
    auth:
      database: grafana
      username: grafana
    extraVolumes:
      - name: config
        configMap:
          name: mysql-config
    extraVolumeMounts:
      - name: config
        mountPath: /opt/bitnami/mysql/conf/
      # authenticationPolicy: caching_sha2_password
