apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  chart:
    spec:
      version: ${MYSQL_VERSION} # Set in postBuild production
  values:
    image:
      debug: true
    primary:
      # extraFlags: "--mysql-native-password=ON --character-set-server=UTF8MB4"
      persistence:
        enabled: true
        storageClass: nfs
        size: 8Gi
      startupProbe:
        enabled: false
        initialDelaySeconds: 600
      livenessProbe:
        enabled: false
        # initialDelaySeconds: 360
        # periodSeconds: 10
        # timeoutSeconds: 5
        # failureThreshold: 6
        # successThreshold: 1
      readinessProbe:
        enabled: false
        # initialDelaySeconds: 360
        # periodSeconds: 5
        # timeoutSeconds: 3
        # failureThreshold: 6
        # successThreshold: 1
      # extraVolumes:
      #   - name: config
      #     configMap:
      #       name: mysql-config
      # extraVolumeMounts:
      #   - name: config
      #     mountPath: /opt/bitnami/mysql/conf/
    secondary:
      replicaCount: 0
    auth:
      database: grafana
      username: grafana
      createDatabase: true
      # authenticationPolicy: caching_sha2_password
