---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tumo-wildcard-tls
  namespace: default
spec:
  secretName: tumo-wildcard-tls-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "monitor,bobby-prod,emqx"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "monitor,bobby-prod,emqx"
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "*.${RESOURCE_DNS}"
  dnsNames:
  - "*.${RESOURCE_DNS}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: canmodi-wildcard-tls
  namespace: default
spec:
  secretName: canmodi-wildcard-tls-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "false"
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "canmodi.com"
  dnsNames:
  - "canmodi.com"
  - "*.canmodi.com"
  - "canmodi.no"
  - "*.canmodi.no"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: garge-wildcard-tls
  namespace: default
spec:
  secretName: garge-wildcard-tls-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "garge-dev,garge-prod"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "garge-dev,garge-prod"
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "garge.no"
  dnsNames:
  - "garge.no"
  - "*.garge.no"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nstuning-wildcard-tls
  namespace: default
spec:
  secretName: nstuning-wildcard-tls-cert
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "nstuning-dev,nstuning-prod"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "nstuning-dev,nstuning-prod"
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "nstuning.no"
  dnsNames:
  - "nstuning.no"
  - "*.nstuning.no"
