---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tumo-wildcard-tls
  namespace: default
spec:
  secretName: tumo-wildcard-tls-cert
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "tumo-wildcard-sync=tumo-wildcard-tls-cert"
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "*.${RESOURCE_DNS}"
  dnsNames:
  - "*.${RESOURCE_DNS}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: canmodi-wildcard-tls
  namespace: default
spec:
  secretName: canmodi-wildcard-tls-cert
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "canmodi-wildcard-sync=canmodi-wildcard-tls-cert"
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "canmodi.com"
  dnsNames:
  - "canmodi.com"
  - "*.canmodi.com"
  - "canmodi.no"
  - "*.canmodi.no"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: garge-wildcard-tls
  namespace: default
spec:
  secretName: garge-wildcard-tls-cert
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "garge-wildcard-sync=garge-wildcard-tls-cert"
  issuerRef:
    kind: ClusterIssuer
    name: ${CERT_ISSUER}
  duration: 2160h # 90d
  renewBefore: 762h # 32d. Let's Encrypt will email an alert if 30d remain and cert has not been renewed.
  commonName: "garge.no"
  dnsNames:
  - "garge.no"
  - "*.garge.no"
