apiVersion: v1
kind: Namespace
metadata:
  name: nstuning-dev
  labels:
    nstuning-wildcard-sync: nstuning-wildcard-tls-cert
---
apiVersion: v1
kind: Namespace
metadata:
  name: nstuning-prod
  labels:
    nstuning-wildcard-sync: nstuning-wildcard-tls-cert
