apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  releaseName: democratic-csi
  chart:
    spec:
      chart: democratic-csi
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  interval: 15m
  timeout: 5m
