apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitor
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    fullnameOverride: prometheus-operator
    nameOverride: prometheus-operator
    grafana:
      enabled: false
    prometheusOperator:
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
    prometheus:
      prometheusSpec:
        retention: 60d # default
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi # default 50Gi
        additionalScrapeConfigs:
          - job_name: 'kubernetes-pods'
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                action: replace
                regex: ([^:]+)(?::\d+)?;(\d+)
                replacement: $1:$2
                target_label: __address__
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: kubernetes_namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: kubernetes_pod_name
    alertmanager:
      config:
        global:
          resolve_timeout: 5m
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: nfs
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 512Mi # default 50Gi
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"