apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bobby-api
  namespace: bobby-prod
spec:
  releaseName: bobby-api
  chart:
    spec:
      chart: bobby-api
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: tumogroup
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
