apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: telegraf
  namespace: monitor
spec:
  releaseName: telegraf
  chart:
    spec:
      chart: telegraf
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: telegraf
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "768Mi"
    config:
      docker: false
      docker_endpoint: ""
    service:
      enabled: false
