apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitor
spec:
  chart:
    spec:
      chart: influxdb
      version: ${INFLUXDB_VERSION} # Set in postBuild production
