apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/pree/helm-charts/tree/master/charts/home-assistant
