apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: ${METALLB_VERSION} # Set in postBuild production
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 15m
  timeout: 5m
  # valuesFrom:
  # - kind: ConfigMap
  #   name: metallb-config