apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${CERT_ISSUER}
spec:
  acme:
    # The ACME server URL
    server: ${ACME_URL}
    # Email address used for ACME registration.
    # Let's Encrypt will use this to contact you about expiring certificates and issues related to your account.
    email: sonyslyst@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: ${CERT_ISSUER}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-dns-secret
