apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "768Mi"
    auth:
      existingSecret: postgresql-secret
