apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: xx # Set by flux patch
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "768Mi"
    auth:
      existingSecret: postgresql-secret
