apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      version: 4.4.2 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  values:
    controller:
      # metrics:
      #   serviceMonitor: null
      resources:
        limits:
          memory: 500Mi
        requests:
          cpu: 100m
          memory: 500Mi