apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      version: ${NGINX_VERSION} # Set in postBuild production
  values:
    controller:
      service:
        ports:
          https: 444
      # metrics:
      #   serviceMonitor: null
      resources:
        limits:
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 1024Mi
      extraArgs:
        tcp-services-configmap: "$(POD_NAMESPACE)/tcp-services"
