apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: ingress-nginx
          namespace: ingress-nginx
        spec:
          chart:
            spec:
              version: 4.3.0 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
          # valuesFrom:
          # - kind: Secret
          #   name: ingress-nginx-ip
          #   valuesKey: config
          values:
            controller:
              resources:
                limits:
                  cpu: "3"
                  memory: 1500Mi
                requests:
                  cpu: 300m
                  memory: 1000Mi
      target:
        kind: HelmRelease
        name: ingress-nginx
        namespace: ingress-nginx
