apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: ingress-nginx
          namespace: ingress-nginx
        spec:
           chart:
              spec:
                 version: ${NGINX_VERSION} # Set in postBuild production
            values:
               controller:
                  # metrics:
                  #    serviceMonitor: null
                  resources:
                     limits:
                        memory: 768Mi
                     requests:
                        cpu: 100m
                        memory: 768Mi
                  # extraArgs: null
                  # priorityClassName: high-priority
      target:
        kind: HelmRelease
        name: ingress-nginx
        namespace: ingress-nginx
