apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: config-syncer
  namespace: kube-system
spec:
  releaseName: config-syncer
  chart:
    spec:
      chart: config-syncer
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: config-syncer
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    config:
      clusterName: ${TUMO_ZONE} # Defined in flux patch
