apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  chart:
    spec:
      chart: redis
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3