apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: descheduler-additional-rules
rules:
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: descheduler-additional-binding
subjects:
  - kind: ServiceAccount
    name: descheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: descheduler-additional-rules
  apiGroup: rbac.authorization.k8s.io
