apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyttogpanne-app
  namespace: pyttogpanne-dev
spec:
  releaseName: pyttogpanne-app
  chart:
    spec:
      chart: pyttogpanne-app
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: tumogroup
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pyttogpanne-app
  namespace: pyttogpanne-prod
spec:
  releaseName: pyttogpanne-app
  chart:
    spec:
      chart: pyttogpanne-app
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: tumogroup
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "500m"
