apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../../components/third-party/bobby-api
  - ../../components/third-party/cert-manager
  - ../../components/third-party/democratic-csi
  - ../../components/third-party/descheduler
  - ../../components/third-party/emqx
  - ../../components/third-party/grafana
  - ../../components/third-party/garge
  - ../../components/third-party/garge-api
  - ../../components/third-party/garge-app
  - ../../components/third-party/garge-operator
  - ../../components/third-party/home-assistant
  - ../../components/third-party/influxdb
  - ../../components/third-party/ingress-nginx
  - ../../components/third-party/kube-prometheus-stack
  - ../../components/third-party/kubed
  - ../../components/third-party/kured
  - ../../components/third-party/metallb
  - ../../components/third-party/metrics-server
  - ../../components/third-party/minecraft
  - ../../components/third-party/mosquitto
  - ../../components/third-party/mysql
  - ../../components/third-party/redis
  - ../../components/third-party/spark-kubernetes-operator
  - ../../components/third-party/telegraf
  - ../../components/third-party/tumogroup
  - ./overlay/third-party/cert-manager
  - ./overlay/third-party/garge-app
  - ./overlay/third-party/home-assistant
  - ./overlay/third-party/home-assistant-et
  - ./overlay/third-party/influxdb
  - ./overlay/third-party/ingress-nginx
  - ./overlay/third-party/mosquitto
  - ./overlay/third-party/mysql
patches:
  - path: ./postBuild.yaml
  - path: ./overlay/third-party/bobby-api/helmRelease.yaml
  - path: ./overlay/third-party/cert-manager/patches.yaml
  - path: ./overlay/third-party/democratic-csi/helmRelease.yaml
  - path: ./overlay/third-party/descheduler/helmRelease.yaml
  - path: ./overlay/third-party/emqx/helmRelease.yaml
  - path: ./overlay/third-party/garge-api/helmRelease.yaml
  - path: ./overlay/third-party/garge-app/helmRelease.yaml
  - path: ./overlay/third-party/garge-operator/helmRelease.yaml
  - path: ./overlay/third-party/grafana/helmRelease.yaml
  - path: ./overlay/third-party/home-assistant-et/helmRelease.yaml
  - path: ./overlay/third-party/home-assistant/helmRelease.yaml
  - path: ./overlay/third-party/influxdb/helmRelease.yaml
  - path: ./overlay/third-party/ingress-nginx/helmRelease.yaml
  - path: ./overlay/third-party/kube-prometheus-stack/helmRelease.yaml
  - path: ./overlay/third-party/kubed/helmRelease.yaml
  - path: ./overlay/third-party/kured/helmRelease.yaml
  - path: ./overlay/third-party/metallb/helmRelease.yaml
  - path: ./overlay/third-party/metrics-server/helmRelease.yaml
  - path: ./overlay/third-party/minecraft-hs/helmRelease.yaml
  - path: ./overlay/third-party/mosquitto/helmRelease.yaml
  - path: ./overlay/third-party/mysql/helmRelease.yaml
  - path: ./overlay/third-party/redis/helmRelease.yaml
  - path: ./overlay/third-party/spark-kubernetes-operator/helmRelease.yaml
  - path: ../../components/third-party/redis/ociRepo.yaml
