apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ../../components/third-party/cert-manager
  - ../../components/third-party/democratic-csi
  - ../../components/third-party/descheduler
  - ../../components/third-party/grafana
  # - ../../components/third-party/grav
  - ../../components/third-party/home-assistant
  - ../../components/third-party/influxdb
  - ../../components/third-party/ingress-nginx
  - ../../components/third-party/kube-prometheus-stack
  - ../../components/third-party/kubed
  - ../../components/third-party/kured
  - ../../components/third-party/metallb
  - ../../components/third-party/metrics-server
  - ../../components/third-party/minecraft
  - ../../components/third-party/mosquitto
  - ../../components/third-party/mysql
  - ../../components/third-party/telegraf
  # - ../../components/third-party/wordpress
  - ./overlay/third-party/cert-manager
  - ./overlay/third-party/descheduler
  # - ./overlay/third-party/grav
  - ./overlay/third-party/home-assistant
  - ./overlay/third-party/home-assistant-et
  - ./overlay/third-party/influxdb
  - ./overlay/third-party/ingress-nginx
  - ./overlay/third-party/mosquitto
  - ./overlay/third-party/mysql
  # - ./overlay/third-party/wordpress
patches:
  - path: ./postBuild.yaml
  - path: ./overlay/third-party/cert-manager/patches.yaml
  - path: ./overlay/third-party/democratic-csi/helmRelease.yaml
  - path: ./overlay/third-party/descheduler/helmRelease.yaml
  - path: ./overlay/third-party/grafana/helmRelease.yaml
  # - path: ./overlay/third-party/grav/helmRelease.yaml
  - path: ./overlay/third-party/home-assistant-et/helmRelease.yaml
  - path: ./overlay/third-party/home-assistant/helmRelease.yaml
  - path: ./overlay/third-party/influxdb/helmRelease.yaml
  - path: ./overlay/third-party/ingress-nginx/helmRelease.yaml
  - path: ./overlay/third-party/kube-prometheus-stack/helmRelease.yaml
  - path: ./overlay/third-party/kubed/helmRelease.yaml
  - path: ./overlay/third-party/kured/helmRelease.yaml
  - path: ./overlay/third-party/metallb/helmRelease.yaml
  - path: ./overlay/third-party/metrics-server/helmRelease.yaml
  - path: ./overlay/third-party/minecraft-hs/helmRelease.yaml
  - path: ./overlay/third-party/mosquitto/helmRelease.yaml
  - path: ./overlay/third-party/mysql/helmRelease.yaml
  - path: ./overlay/third-party/telegraf/helmRelease.yaml
  # - path: ./overlay/third-party/wordpress/helmRelease.yaml
