apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      FLUX_CONFIG_PATH: ./clusters/production
      TUMO_ZONE: prod # dev | playground | prod
      TUMO_ENVIRONMENT: prod # prod
      CERT_MANAGER_VERSION: 1.15.3 # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      DEMOCRATIC_CSI_VERSION: 0.14.6 # https://artifacthub.io/packages/helm/democratic-csi/democratic-csi
      GRAFANA_VERSION: 8.4.6 # https://artifacthub.io/packages/helm/grafana/grafana
      HOME_ASSISTANT_VERSION: 0.19.0 # https://artifacthub.io/packages/helm/alekc/home-assistant
      INFLUXDB_VERSION: 6.3.18 # https://artifacthub.io/packages/helm/bitnami/influxdb
      KUBED_VERSION: 0.13.2 # https://artifacthub.io/packages/helm/appscode/kubed
      KURED_VERSION: 5.5.0 # https://artifacthub.io/packages/helm/kured/kured
      METALLB_VERSION: 0.14.8 # https://artifacthub.io/packages/helm/metallb/metallb
      METRICS_VERSION: 3.12.1 # https://artifacthub.io/packages/helm/metrics-server/metrics-server
      MINECRAFT_VERSION: 4.21.0 # https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft
      MOSQUITTO_VERSION: 16.0.1 # https://artifacthub.io/packages/helm/truecharts/mosquitto
      MYSQL_VERSION: 11.1.15 # https://artifacthub.io/packages/helm/bitnami/mysql
      NGINX_VERSION: 4.11.2 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      PROMETHEUS_VERSION: 62.0.0 # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
      TELEGRAF_VERSION: 1.8.53 # https://artifacthub.io/packages/helm/influxdata/telegraf
    substituteFrom:
      - kind: ConfigMap
        name: tumo-flux-config
