apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      FLUX_CONFIG_PATH: ./clusters/production
      TUMO_ZONE: prod # dev | playground | prod
      TUMO_ENVIRONMENT: prod # prod
      CERT_MANAGER_VERSION: 1.17.1 # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      DEMOCRATIC_CSI_VERSION: 0.14.7 # https://artifacthub.io/packages/helm/democratic-csi/democratic-csi
      DESCHEDULER_VERSION: 0.32.2 # https://artifacthub.io/packages/helm/descheduler/descheduler
      GRAFANA_VERSION: 8.10.1 # https://artifacthub.io/packages/helm/grafana/grafana
      HOME_ASSISTANT_VERSION: 1.2.0 # https://artifacthub.io/packages/helm/alekc/home-assistant
      HOME_ASSISTANT_VERSION_ET: 1.2.0 # https://artifacthub.io/packages/helm/alekc/home-assistant
      INFLUXDB_VERSION: 6.6.0 # https://artifacthub.io/packages/helm/bitnami/influxdb
      KUBED_VERSION: 0.13.2 # https://artifacthub.io/packages/helm/appscode/kubed
      KURED_VERSION: 5.6.0 # https://artifacthub.io/packages/helm/kured/kured
      METALLB_VERSION: 0.14.9 # https://artifacthub.io/packages/helm/metallb/metallb
      METRICS_VERSION: 3.12.2 # https://artifacthub.io/packages/helm/metrics-server/metrics-server
      MINECRAFT_VERSION: 4.23.7 # https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft
      MOSQUITTO_VERSION: 16.0.1 # https://artifacthub.io/packages/helm/truecharts/mosquitto
      MYSQL_VERSION: 12.3.0 # https://artifacthub.io/packages/helm/bitnami/mysql
      NGINX_VERSION: 4.12.0 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      PROMETHEUS_VERSION: 69.6.0 # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
      TELEGRAF_VERSION: 1.8.55 # https://artifacthub.io/packages/helm/influxdata/telegraf
    substituteFrom:
      - kind: ConfigMap
        name: tumo-flux-config
