apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      FLUX_CONFIG_PATH: ./clusters/production
      TUMO_ZONE: prod # dev | playground | prod
      TUMO_ENVIRONMENT: prod # prod
      NGINX_VERSION: 4.8.3 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      METALLB_VERSION: 0.13.12 # https://artifacthub.io/packages/helm/metallb/metallb
      METRICS_VERSION: 3.11.0 # https://artifacthub.io/packages/helm/metrics-server/metrics-server
      CERT_MANAGER_VERSION: 1.13.2 # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      HOME_ASSISTANT_VERSION: 1.29.2 # https://artifacthub.io/packages/helm/pree-helm-charts/home-assistant?modal=install
      MOSQUITTO_VERSION: 11.0.13 # https://artifacthub.io/packages/helm/truecharts/mosquitto
      KUBED_VERSION: 0.13.2 # https://artifacthub.io/packages/helm/appscode/kubed
    substituteFrom:
      - kind: ConfigMap
        name: tumo-flux-config
