apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      FLUX_CONFIG_PATH: ./clusters/production
      TUMO_ZONE: prod # dev | playground | prod
      TUMO_ENVIRONMENT: prod # prod
      NGINX_VERSION: 4.8.3 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      METALLB_VERSION: 0.13.12 # https://artifacthub.io/packages/helm/metallb/metallb
    substituteFrom:
    - kind: ConfigMap
      name: tumo-flux-config