apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      version: ${MOSQUITTO_VERSION} # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: mosquitto
        namespace: flux-system
  values:
    auth:
      enabled: true
      secretName: mosquittoconf
      users:
        - username: admin
    service:
      port: 1883
      type: LoadBalancer
    persistence:
      data:
        storageClass: nfs
        size: 5Gi
      configinc:
        storageClass: nfs
        size: 128Mi
  interval: 15m
  timeout: 5m
