apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      version: ${MOSQUITTO_VERSION} # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: mosquitto
        namespace: flux-system
  values:
    auth:
      enabled: true
    websockets:
      enabled: true
    configmap:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            password_file /mosquitto/passwords/passwords.conf
    persistence:
      data:
        storageClass: nfs
        size: 5Gi
        mountPath: "/mosquitto/data"
      configinc:
        storageClass: nfs
        size: 128Mi
        mountPath: "/mosquitto/configinc"
    extraVolumes:
      - name: password
        secret:
          secretName: mosquittoconf
    extraVolumeMounts:
      - name: password
        mountPath: /mosquitto/passwords/passwords.conf
        subPath: password
  interval: 15m
  timeout: 5m