apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: ./charts/stable/mosquitto
      # version: ${MOSQUITTO_VERSION} # Set by flux patch
      sourceRef:
        kind: GitRepository
        name: truecharts
        namespace: flux-system
  values:
    auth:
      enabled: true
    service:
      main:
        type: LoadBalancer
        ports:
          main:
            port: 1883
            targetPort: 1883
    configmap:
      config:
        enabled: true
        data:
          mosquitto.conf: |
            password_file /mosquitto/passwords/passwords.conf
    persistence:
      data:
        enabled: true
        mountPath: "/mosquitto/data"
      configinc:
        enabled: true
        mountPath: "/mosquitto/configinc"
      mosquitto-config:
        enabled: true
        mountPath: "/mosquitto/config/mosquitto.conf"
        subPath: "mosquitto.conf"
        type: configmap
        objectName: config
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mosquitto
        spec:
          template:
            spec:
              containers:
              - name: mosquitto
                volumeMounts:
                - mountPath: /mosquitto/passwords/passwords.conf
                  name: mosquittoconf
                  readOnly: true
              volumes:
              - name: mosquittoconf
                secret:
                  secretName: mosquittoconf
  interval: 15m
  timeout: 5m
