apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitor
spec:
  releaseName: influxdb
  chart:
    spec:
      chart: influxdb
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: influxdb
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    influxdb:
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
    auth:
      existingSecret: influxdb-secret
