apiVersion: "descheduler/v1alpha2"
kind: "DeschedulerPolicy"
profiles:
  - name: PodLifeTime
    pluginConfig:
    - name: "PodLifeTime"
      args:
        maxPodLifeTimeSeconds: 86400
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: telegraf
    plugins:
      deschedule:
        enabled:
          - "PodLifeTime"