apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telegraf-ds
  namespace: monitor
spec:
  chart:
    spec:
      chart: telegraf-ds
      version: ${TELEGRAF_VERSION} # Set in postBuild production
  valuesFrom:
    - secretKeyRef:
        name: influxdb-credentials
    - secretKeyRef:
        name: mosquitto-credentials
  values:
    config:
      inputs:
        - mqtt_consumer:
            servers: ["tcp://mqtt.prod.tumogroup.com:1883"]
            topics: ["home/#"]
            qos: 0
            connection_timeout: "30s"
            max_undelivered_messages: 1000
            username: "{{ .Values.username }}"
            password: "{{ .Values.password }}"
      outputs:
        - influxdb_v2:
            urls: ["https://influxdb.prod.tumogroup.com"]
            token: "{{ .Values.token }}"
            organization: "{{ .Values.organization }}"
            bucket: "{{ .Values.bucket }}"
