apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  chart:
    spec:
      version: ${KURED_VERSION} # Set in postBuild production
  values:
    extraArgs:
      start-time: 2am
      end-time: 4am
      drain-timeout: 15m
      force-reboot: true
