apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      version: ${WORDPRESS_VERSION} # Set in postBuild production
  values:
    resources:
      requests:
        cpu: "200m"
        memory: "768Mi"
    existingSecret: wordpress-secret
    containerSecurityContext:
      enabled: false
    wordpressConfigureCache: true
    memcached:
      enabled: true
      auth:
        enabled: true
        username: "wordpresscaching"
        existingPasswordSecret: wordpress-secret
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    podSecurityContext:
      enabled: false
    persistence:
      enabled: true
      storageClass: nfs
      size: 10Gi
      accessModes:
        - ReadWriteMany
    mariadb:
      primary:
        containerSecurityContext:
          enabled: false
        podSecurityContext:
          enabled: false
        persistence:
          enabled: true
          storageClass: nfs
          size: 10Gi
          accessModes:
            - ReadWriteMany
