apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      version: ${WORDPRESS_VERSION} # Set in postBuild production
  values:
    persistence:
      enabled: true
      storageClass: nfs
      size: 10Gi
    mariadb:
      primary:
        persistence:
          enabled: true
          storageClass: nfs
          size: 10Gi