apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      version: ${WORDPRESS_VERSION} # Set in postBuild production
  values:
    resources:
      requests:
        cpu: "500m"
        memory: "768Mi"
    existingSecret: wordpress-secret
    containerSecurityContext:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: nginx
      tls: true
      hostname: wordpress1.prod.tumogroup.com
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
    wordpressConfigureCache: true
    memcached:
      enabled: true
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    podSecurityContext:
      enabled: false
    persistence:
      enabled: true
      storageClass: nfs
      size: 10Gi
      accessModes:
        - ReadWriteMany
    mariadb:
      primary:
        containerSecurityContext:
          enabled: false
        podSecurityContext:
          enabled: false
        persistence:
          enabled: true
          storageClass: nfs
          size: 10Gi
          accessModes:
            - ReadWriteMany
