apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  chart:
    spec:
      version: ${WORDPRESS_VERSION} # Set in postBuild production
  values:
    existingSecret: wordpress-secret
    image:
      debug: true
    ingress:
      enabled: true
      hostname: wordpress1.prod.tumogroup.com
    containerSecurityContext:
      enabled: false
    memcached:
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
    podSecurityContext:
      enabled: false
    persistence:
      enabled: true
      storageClass: nfs
      size: 10Gi
    mariadb:
      primary:
        containerSecurityContext:
          enabled: false
        podSecurityContext:
          enabled: false
        persistence:
          enabled: true
          storageClass: nfs
          size: 10Gi
