apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/server-snippet: |
      location ~* "^/" {
        proxy_set_header "X-Forwarded-For $proxy_add_x_forwarded_for";
        proxy_set_header "Upgrade $http_upgrade";
        proxy_set_header "Connection $connection_upgrade";
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "home-assistant.prod.tumogroup.com"
  rules:
    - host: home-assistant.prod.tumogroup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
