apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  namespace: home-assistant
  annotations:
    meta.helm.sh/release-name: home-assistant
    meta.helm.sh/release-namespace: home-assistant
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "home-assistant.prod.tumogroup.com"
      secretName: home-assistant-tls
  rules:
    - host: home-assistant.prod.tumogroup.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123
