apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-storage
spec:
  storageClassName: kubernetes-storage
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/kubernetes/kubernetes-storage"