apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  releaseName: democratic-csi
  chart:
    spec:
      chart: democratic-csi
      version: ${DEMOCRATIC_CSI_VERSION} # Set in postBuild production
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.nfs"
    storageClasses:
    - name: freenas-nfs-csi
      defaultClass: false
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
          
      mountOptions:
      - noatime
      - nfsvers=4
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    driver:
      config:
        driver: freenas-nfs
        instance_id:
        volume_context_name: true
        httpConnection:
          apiKeySecretRef:
            name: api-key-secret
            key: apikey
          protocol: http
          host: truenas.local
          port: 80
          allowInsecure: true
          apiVersion: 2
        sshConnection:
          host: truenas.local
          port: 22
          username: csi
          privateKeySecretRef:
            name: private-key-secret
            key: privatekey
        zfs:
          datasetParentName: "mnt/kubernetes/vols"
          detachedSnapshotsDatasetParentName: mnt/kubernetes/snaps
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: "root"
          datasetPermissionsGroup: "wheel"
        nfs:
          shareHost: truenas.local
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: wheel
          shareMapallUser: ""
          shareMapallGroup: ""
    node:
      driver:
        config:
          iscsi:
            interface: default
  interval: 15m
  timeout: 5m
