apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  releaseName: democratic-csi
  chart:
    spec:
      chart: democratic-csi
      version: ${DEMOCRATIC_CSI_VERSION} # Set in postBuild production
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    csiDriver:
      name: "org.democratic-csi.nfs-client"
    storageClasses:
    - name: democratic-nfs-client
      defaultClass: true
      reclaimPolicy: Retain
      volumeBindingMode: Immediate
      allowVolumeExpansion: false
      parameters:
        fsType: nfs
      mountOptions:
      - noatime
      - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    volumeSnapshotClasses: []
    controller:
      enabled: true
      externalResizer:
        enabled: false
      strategy: deployment
      hostNetwork: true
      hostIPC: true
      driver:
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "mkdir -p /kubernetes; mount truenas.local:/mnt/kubernetes /kubernetes"]
          preStop:
            exec:
              command: ["/bin/sh","-c","umount /kubernetes"]
    driver:
      config:
        driver: nfs-client
        instance_id:
        httpConnection:
          protocol: http
          host: truenas.local
          port: 80
          allowInsecure: true
        nfs:
          shareHost: truenas.local
          shareBasePath: "/mnt/kubernetes"
          controllerBasePath: "/kubernetes"
          dirPermissionsMode: "0700"
          dirPermissionsUser: 1000
          dirPermissionsGroup: 1000
  interval: 15m
  timeout: 5m
