apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: democratic-csi
  namespace: democratic-csi
spec:
  releaseName: democratic-csi
  chart:
    spec:
      chart: democratic-csi
      version: ${DEMOCRATIC_CSI_VERSION} # Set in postBuild production
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  values:
    controller:
      driver:
        enabled: true
        image:
          registry: docker.io/democraticcsi/democratic-csi
          tag: next
    csiDriver:
      name: "nfs"
    storageClasses:
      - name: nfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: nfs
          detachedVolumesFromSnapshots: "false"
        mountOptions:
          - noatime
          - nfsvers=3
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:
    volumeSnapshotClasses: []
    driver:
      existingConfigSecret: api-key-secret
      config:
        driver: freenas-api-nfs
  interval: 15m
  timeout: 5m
