apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: spark-kubernetes-operator
  namespace: flux-system
spec:
  interval: 10m
  url: https://apache.github.io/spark-kubernetes-operator/
