apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spark-kubernetes-operator
  namespace: spark-kubernetes-operator
spec:
  releaseName: spark-kubernetes-operator
  chart:
    spec:
      chart: spark-kubernetes-operator
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: spark-kubernetes-operator
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
