apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crowdsec
  namespace: crowdsec
spec:
  releaseName: crowdsec
  chart:
    spec:
      chart: crowdsec
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: crowdsec
        namespace: flux-system
  interval: 5m
  install:
    disableSchemaValidation: true
    remediation:
      retries: 3
  upgrade:
    disableSchemaValidation: true
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    container_runtime: containerd
    config:
      parsers:
        s02-enrich:
          pod-network-whitelist.yaml: |
            name: tumo/pod-network-whitelist
            description: Whitelist the cluster pod network
            whitelist:
              reason: cluster pod network
              cidr:
                - "192.169.0.0/16"
      profiles.yaml: |
        name: escalating_ip_remediation
        filters:
          - Alert.Remediation == true && Alert.GetScope() == "Ip"
        decisions:
          - type: ban
            duration: 4h
        duration_expr: "Sprintf('%dh', min(720, 4 * (GetDecisionsSinceCount(Alert.GetValue(), '30d') + 1) * (GetDecisionsSinceCount(Alert.GetValue(), '30d') + 1)))"
        on_success: break
        ---
        name: default_range_remediation
        filters:
          - Alert.Remediation == true && Alert.GetScope() == "Range"
        decisions:
          - type: ban
            duration: 4h
        on_success: break
      simulation.yaml: |
        simulation: false
      config.yaml.local: |
        api:
          server:
            auto_registration:
              enabled: true
              token: "$${REGISTRATION_TOKEN}"
              allowed_ranges:
                - "127.0.0.1/32"
                - "192.168.0.0/16"
                - "192.169.0.0/16"
                - "10.0.0.0/8"
                - "172.16.0.0/12"
    lapi:
      env:
      - name: BOUNCER_KEY_traefik
        valueFrom:
          secretKeyRef:
            name: crowdsec-bouncer-key
            key: BOUNCER_KEY_traefik
      persistentVolume:
        data:
          storageClassName: nfs
        config:
          storageClassName: nfs
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    agent:
      isDeployment: true
      replicas: 1
      serviceAccountName: crowdsec-agent
      hostVarLog: false
      acquisition: []
      additionalAcquisition:
      - source: kubernetes
        namespace: traefik
        selector: app.kubernetes.io/name=traefik
        labels:
          type: traefik
      env:
      - name: COLLECTIONS
        value: crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/whitelist-good-actors
      metrics:
        serviceMonitor:
          enabled: true
      resources:
        limits:
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
