apiVersion: v1
kind: ServiceAccount
metadata:
  name: crowdsec-agent
  namespace: crowdsec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crowdsec-agent-pod-logs
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crowdsec-agent-pod-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crowdsec-agent-pod-logs
subjects:
- kind: ServiceAccount
  name: crowdsec-agent
  namespace: crowdsec
