apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault-transit
spec:
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
