apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: config-syncer
  namespace: kube-system
spec:
  chart:
    spec:
      version: ${CONFIG_SYNCER_VERSION} # Set in postBuild production
