apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      version: ${VAULT_VERSION} # Set in postBuild production
  values:
    ui:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
        port: 8200
    server:
      ha:
        enabled: true
        replicas: 5
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true

            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }

            storage "raft" {
              path = "/vault/data"
            }

            seal "transit" {
              address = "http://vault.vault-transit.svc:8200"
              token   = "${VAULT_UNSEAL_TOKEN}"
              key_name = "autounseal"
              mount_path = "transit/"
              tls_skip_verify = true
            }

            service_registration "kubernetes" {}
      dataStorage:
        storageClass: nfs
      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      livenessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60
      auditStorage:
        enabled: true
        storageClass: nfs
      standalone:
        enabled: false
      extraSecretEnvironmentVars:
        - envName: VAULT_UNSEAL_TOKEN
          secretName: vault-b-unseal-token
          secretKey: token
      resources:
        requests:
          memory: 8Gi
          cpu: 2000m
        limits:
          memory: 8Gi
          cpu: 2000m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault-transit
spec:
  chart:
    spec:
      chart: vault
      version: ${VAULT_VERSION} # Set in postBuild production
  values:
    ui:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
        port: 8200
    server:
      dataStorage:
        storageClass: nfs
      auditStorage:
        enabled: true
        storageClass: nfs
      standalone:
        enabled: true
      resources:
        requests:
          memory: 8Gi
          cpu: 2000m
        limits:
          memory: 8Gi
          cpu: 2000m
