apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    spec:
      chart: vault
      version: ${VAULT_VERSION} # Set in postBuild production
  values:
    ui:
      enabled: true
      service:
        enabled: true
        type: ClusterIP
        port: 8200
    server:
      ha:
        enabled: true
        replicas: 5
      dataStorage:
        storageClass: nfs
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        pathType: Prefix
        hosts:
          - host: vault.prod.tumogroup.com
            paths:
              - path: /
        tls:
          - secretName: vault-tls
            hosts:
              - vault.prod.tumogroup.com
      readinessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
      livenessProbe:
        enabled: true
        path: "/v1/sys/health?standbyok=true"
        initialDelaySeconds: 60
        auditStorage:
          enabled: true
          storageClass: nfs
      standalone:
        enabled: false
      resources:
        requests:
          memory: 8Gi
          cpu: 2000m
        limits:
          memory: 8Gi
          cpu: 2000m


