apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: ${METRICS_VERSION} # Set in postBuild development
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  interval: 5m
  timeout: 5m
  install:
    remediation:
      retries: 3
