apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  chart:
    spec:
      chart: emqx
      version: ${EMQX_VERSION} # Set in postBuild production
  values:
    # volumes:
    #   - name: ssl-volume
    #     secret:
    #       secretName: emqx-mqtt-tls
    # volumeMounts:
    #   - name: ssl-volume
    #     mountPath: /tmp/ssl
    #     readOnly: true
    # emqxConfig:
    #   EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE: /tmp/ssl/tls.crt
    #   EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE: /tmp/ssl/tls.key
    #   EMQX_LISTENERS__TCP__DEFAULT__PROXY_PROTOCOL: "true"
    persistence:
      enabled: true
      storageClassName: nfs
      size: 1Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
    service:
      type: LoadBalancer
    ingress:
      dashboard:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        pathType: Prefix
        path: /
        hosts:
          - emqx-dashboard.prod.tumogroup.com
        tls:
          - secretName: emqx-dashboard-tls
            hosts:
              - emqx-dashboard.prod.tumogroup.com
      mqtt:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        pathType: Prefix
        path: /
        hosts:
          - emqx-mqtt.prod.tumogroup.com
        tls:
          - secretName: emqx-mqtt-tls
            hosts:
              - emqx-mqtt.prod.tumogroup.com
      ssl:
        enabled: true
        commonName: emqx-mqtt.prod.tumogroup.com
        dnsnames:
          - emqx-mqtt.prod.tumogroup.com
        issuer:
          name: letsencrypt-prod
          kind: ClusterIssuer
    metrics:
      enabled: true
