apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emqx
  namespace: emqx
spec:
  chart:
    spec:
      chart: emqx
      version: ${EMQX_VERSION} # Set in postBuild production
  values:
    persistence:
      enabled: true
      storageClassName: nfs
      size: 1Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
    service:
      type: LoadBalancer
    ingress:
      dashboard:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        pathType: Prefix
        path: /
        hosts:
          - emqx-dashboard.prod.tumogroup.com
        tls:
          - secretName: emqx-dashboard-tls
            hosts:
              - emqx-dashboard.prod.tumogroup.com
      mqtt:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        pathType: Prefix
        path: /
        hosts:
          - emqx-mqtt.prod.tumogroup.com
        tls:
          - secretName: emqx-mqtt-tls
            hosts:
              - emqx-mqtt.prod.tumogroup.com
    metrics:
      enabled: true
