apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path-provisioner
  namespace: local-path-provisioner
spec:
  releaseName: local-path-provisioner
  chart:
    spec:
      chart: local-path-provisioner
      version: ${LOCAL_PATH_PROVISIONER_VERSION} # Set in postBuild production
      sourceRef:
        kind: HelmRepository
        name: local-path-provisioner
        namespace: flux-system
  interval: 15m
  timeout: 5m
