apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  chartRef:
    kind: postgresql
    name: kubernetes-event-exporter
    namespace: flux-system
  values:
    auth:
      existingSecret: postgresql-secret
      secretKeys:
        adminPasswordKey: "adminPasswordKey"
        userPasswordKey: "userPasswordKey"
        replicationPasswordKey: "replicationPasswordKey"
    primary:
      persistence:
        enabled: true
        storageClass: nfs
        size: 8Gi
    backup:
      enabled: true
      cronjob:
        storage:
          enabled: true
          storageClass: nfs
          size: 8Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
