apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  # chart:
  #   spec:
  #     chart: redis
  #     version: ${REDIS_VERSION} # Set in postBuild production
  values:
    architecture: replication
    global:
      defaultStorageClass: nfs
    master:
      persistence:
        storageClass: nfs
    replica:
      persistence:
        storageClass: nfs
    sentinel:
      enabled: true
      persistence:
        storageClass: nfs
    metrics:
      enabled: true

