apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grav
  namespace: grav
spec:
  releaseName: grav
  chart:
    spec:
      chart: ./charts/stable/grav
      version: ${GRAV_VERSION} # Set by flux patch
      sourceRef:
        kind: GitRepository
        name: truecharts
        namespace: flux-system
  values:
    persistence:
      config:
        enabled: true
        mountPath: "/config"
  interval: 15m
  timeout: 5m
