apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitor
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "250Mi"
    nodeSelector: {"kubernetes.io/os": "linux"}
    env:
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_SSL_MODE: "skip-verify"
      GF_DATABASE_CA_CERT_PATH: /etc/ssl/certs/ca-certificates.crt
    envFromSecret: grafana-secrets
  valuesFrom:
  - kind: Secret
    name: grafana-helm-secret
    valuesKey: config