apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/truecharts/charts
  ref:
    branch: master
