apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: mosquitto
        namespace: flux-system
  values:
    persistence:
      data:
        storageClass: "local-path"
      configinc:
        storageClass: "local-path"
  interval: 15m
  timeout: 5m
