apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: mosquitto
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: ./charts/stable/mosquitto
      version: xx # Set by flux patch
      sourceRef:
        kind: GitRepository
        name: truecharts
        namespace: flux-system
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
  interval: 15m
  timeout: 5m
