apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs
        namespace: flux-system
  values:
    apiService:
        insecureSkipTLSVerify: true
    resources:
      requests:
        cpu: 100m
        memory: 200mi
  interval: 5m
  timeout: 5m
  install:
    remediation:
      retries: 3
