apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  chart:
    spec:
      chart: minecraft
      version: ${MINECRAFT_VERSION} # Set in postBuild production
  values:
    resources:
      requests:
        cpu: "500m"
        memory: "5120Mi"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "SPIGOT"
      maxWorldSize: 1000000
      ops: "sonyslyst,haasjo"
      icon: "https://static.miraheze.org/windowswallpaperwiki/thumb/0/06/Koala.jpg/200px-Koala.jpg"
      memory: 5120M
      serviceType: LoadBalancer
      downloadWorldUrl: "https://drive.usercontent.google.com/download?id=10NLGCr98FLunpo9XJ7sj3WdW5uYC54nI&export=download&authuser=0&confirm=t&uuid=d66322cf-0cbc-4b2c-bce6-7e32ed5f1d3a&at=APZUnTW8jBXQxTrgHucFM2MttUfR%3A1713279653608"
      forceReDownload: true
    persistence:
      storageClass: nfs
      dataDir:
        enabled: true
        Size: 10Gi
    mcbackup:
      enabled: true    
      persistence:
      storageClass: nfs
      backupDir:
        enabled: true
        Size: 10Gi
