apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  chart:
    spec:
      chart: minecraft
      version: ${MINECRAFT_VERSION} # Set in postBuild production
  values:
    resources:
      requests:
        cpu: "1500m"
        memory: "10Gi"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "SPIGOT"
      maxWorldSize: 1000000
      ops: "sonyslyst,haasjo"
      icon: "https://static.miraheze.org/windowswallpaperwiki/thumb/0/06/Koala.jpg/200px-Koala.jpg"
      memory: 10G
      serviceType: LoadBalancer
    persistence:
      storageClass: nfs
      dataDir:
        enabled: true
        Size: 10Gi
    mcbackup:
      enabled: true    
      persistence:
      storageClass: nfs
      backupDir:
        enabled: true
        Size: 10Gi
