apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  chart:
    spec:
      chart: minecraft
      version: ${MINECRAFT_VERSION} # Set in postBuild production
  values:
    resources:
      requests:
        cpu: "8000m"
        memory: "16Gi"
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "PAPER"
      maxWorldSize: 50000
      ops: "sonyslyst,haasjo"
      icon: "https://static.miraheze.org/windowswallpaperwiki/thumb/0/06/Koala.jpg/200px-Koala.jpg"
      memory: 16G
      serviceType: LoadBalancer
      pluginUrls: [
        "https://dev.bukkit.org/projects/chunky-pregenerator/files/latest",
        "https://dev.bukkit.org/projects/thizzyz-tree-feller/files/5539016/download",
        "https://dev.bukkit.org/projects/craftbay/files/latest"
      ]
    persistence:
      storageClass: nfs
      dataDir:
        enabled: true
        Size: 10Gi
    mcbackup:
      enabled: true    
      persistence:
      storageClass: nfs
      backupDir:
        enabled: true
        Size: 10Gi
