apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitor
spec:
  chart:
    spec:
      version: ${PROMETHEUS_VERSION} # Set in postBuild production
  values:
    prometheus:
      prometheusSpec:
        retention: 60d # default
        resources:
          requests:
            cpu: "1"
            memory: "4Gi"

