apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: telegraf
  namespace: monitor
spec:
  chart:
    spec:
      chart: telegraf
      version: ${TELEGRAF_VERSION} # Set in postBuild production
  values:
    replicaCount: 2
    env:
      - name: MOSQUITTO_USERNAME
        valueFrom:
          secretKeyRef:
            name: mosquitto-credentials
            key: username
      - name: MOSQUITTO_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mosquitto-credentials
            key: password
      - name: INFLUXDB_TOKEN
        valueFrom:
          secretKeyRef:
            name: influxdb-credentials
            key: token
      - name: INFLUXDB_ORGANIZATION
        valueFrom:
          secretKeyRef:
            name: influxdb-credentials
            key: organization
      - name: INFLUXDB_BUCKET
        valueFrom:
          secretKeyRef:
            name: influxdb-credentials
            key: bucket
    config:
      agent:
        debug: true
      inputs:
        - mqtt_consumer:
            servers: ["tcp://mqtt.prod.tumogroup.com:1883"]
            topics: ["home/#"]
            qos: 0
            connection_timeout: "30s"
            max_undelivered_messages: 1000
            username: "$MOSQUITTO_USERNAME"
            password: "$MOSQUITTO_PASSWORD"
            data_format: "json"
      outputs:
        - influxdb_v2:
            urls: 
              - "https://influxdb.prod.tumogroup.com"
            token: "$INFLUXDB_TOKEN"
            organization: "$INFLUXDB_ORGANIZATION"
            bucket: "$INFLUXDB_BUCKET"
