apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  releaseName: mysql
  chartRef:
    kind: OCIRepository
    name: mysql
    namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "768Mi"
    auth:
      existingSecret: mysql-secret
