apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitor
spec:
  releaseName: alloy
  chart:
    spec:
      chart: alloy
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  dependsOn:
    - name: loki
      namespace: monitor
  values:
    alloy:
      configMap:
        content: |
          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets

            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              target_label  = "node"
            }
            rule {
              source_labels = ["__meta_kubernetes_pod_label_logformat"]
              target_label  = "logformat"
            }
          }

          loki.source.kubernetes "pod_logs" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.process.pod_logs.receiver]
          }

          loki.process "pod_logs" {
            forward_to = [loki.write.default.receiver]

            stage.match {
              selector = "{logformat=\"serilog\"}"

              stage.multiline {
                firstline     = "^\\[\\d{2}:\\d{2}:\\d{2} (VRB|DBG|INF|WRN|ERR|FTL)\\]"
                max_wait_time = "3s"
              }

              stage.regex {
                expression = "^\\[\\d{2}:\\d{2}:\\d{2} (?P<level>VRB|DBG|INF|WRN|ERR|FTL)\\]"
              }

              stage.labels {
                values = { level = "" }
              }
            }
          }

          loki.write "default" {
            endpoint {
              url = "http://loki.monitor.svc.cluster.local:3100/loki/api/v1/push"
            }
          }
    controller:
      type: daemonset
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
