apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nstuning-redirect
  namespace: nstuning-prod
spec:
  redirectRegex:
    regex: "^https?://[^/]+/(.*)"
    replacement: "https://www.nstuning.no/${1}"
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nstuning-redirect
  namespace: nstuning-prod
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`nstuning.no`)
    middlewares:
    - name: nstuning-redirect
    services:
    - name: noop@internal
      kind: TraefikService
  tls:
    secretName: nstuning-wildcard-tls-cert
