apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 15m
  timeout: 5m
  # valuesFrom:
  # - kind: ConfigMap
  #   name: metallb-config
  #   valuesKey: values.yaml # This is the default, but best to be explicit for clarity