name: Check for new versions
on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
    inputs:
      sourceCluster:
        description: "Source cluster"
        required: false
        type: choice
        options:
          - "production"
        default: "production"
      destinationCluster:
        description: "Destination cluster"
        required: false
        type: choice
        options:
          - "production"
        default: "production"

jobs:
  check-version:
    name: Check for new versions
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set environments
        run: |
          PR_BRANCH_TEMP="automatic-version-update"
          PR_NAME_TEMP="Automatic Pull Request"
          destinationCluster="${{ inputs.destinationCluster }}"

          if [ -z $destinationCluster ]; then
            destinationCluster="production"
          fi

          echo "PR_BRANCH=${PR_BRANCH_TEMP}-${destinationCluster}" >> $GITHUB_ENV
          echo "PR_NAME=${PR_NAME_TEMP} - ${destinationCluster}" >> $GITHUB_ENV
      - name: Check version
        id: checkversion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCE_CLUSTER: ${{ inputs.sourceCluster }}
          DESTINATION_CLUSTER: ${{ inputs.destinationCluster }}
        run: .github/workflows/scripts/update_components.sh

      - name: Create PR
        if: ${{ steps.checkversion.outputs.numberOfChanges > 0 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_BRANCH: ${{ env.PR_BRANCH }}
          PR_NAME: ${{ env.PR_NAME }}
        run: .github/workflows/scripts/create_pr.sh
