name: Code scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every Wednesday at 00:00 UTC.
    - cron: 0 0 * * 3
      timezone: "Europe/Oslo"

permissions: {}

jobs:
  github-actions:
    # Scan GitHub Actions workflow files for security vulnerabilities.
    name: GitHub Actions
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: equinor/ops-actions/.github/workflows/zizmor-codeql.yml@8cf05342045a745a619bce94b04f235051a2a068 # v9.38.4
