name: Code scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every Wednesday at 00:00 UTC.
    - cron: 0 0 * * 3
      timezone: "Europe/Oslo"

permissions: {}

jobs:
  github-actions:
    # Scan GitHub Actions workflow files for security vulnerabilities.
    name: GitHub Actions
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: equinor/ops-actions/.github/workflows/zizmor-codeql.yml@04eae1eb46f52241507c15ab0e874b9063ccf4d0 # v9.40.1
