name: Code scanning

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # Run every Wednesday at 00:00 UTC.
    - cron: 0 0 * * 3
      timezone: "Europe/Oslo"

permissions: {}

jobs:
  github-actions:
    # Scan GitHub Actions workflow files for security vulnerabilities.
    name: GitHub Actions
    permissions:
      contents: read
      actions: read
      security-events: write
    uses: equinor/ops-actions/.github/workflows/zizmor-codeql.yml@a98fb1dafcfb1acdeea610e70eb8c1a2be6b59cd # v9.39.2
