name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      vault_addr:
        description: 'Vault Address'
        required: true
        default: 'http://vault.vault-transit.svc:8200'


jobs:
  dev:
    uses: equinor/ops-actions/.github/workflows/docker.yml@7250ebf9722b3e8ed96a427b36f8eb2df7512e81
    secrets:
        password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      environment: prod
      registry: registry.hub.docker.com
      username: sondresjo
      repository: sondresjo/vault-transit-bootstrap
      working_directory: ./clusters/production/overlay/third-party/vault
      build_args: |
        VAULT_ADDR=${{ github.event.inputs.vault_addr }}
      tag: latest
