name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  dev:
    uses: equinor/ops-actions/.github/workflows/docker.yml@7250ebf9722b3e8ed96a427b36f8eb2df7512e81
    secrets:
        password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      environment: prod
      registry: registry.hub.docker.com
      username: sondresjo
      repository: sondresjo/vault-transit-bootstrap
      working_directory: ./clusters/production/overlay/third-party/vault
      tag: latest
